######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 17 19:16:11 2013
######################################################################

TEMPLATE = app
TARGET = QTry
INCLUDEPATH += . /usr/include/qt5/QtWidgets/

# Input
SOURCES += main.cpp
